interface rulesModalProps {
	setIsOpen: (value: boolean) => void;
}

export const RulesModal: React.FC<rulesModalProps> = ({ setIsOpen }) => {
	return (
		<div
			id='authentication-modal'
			tab-index='-1'
			className='fixed top-0 left-0 right-0 z-50 w-screen h-screen p-4 overflow-x-hidden overflow-y-auto md:inset-0 flex justify-center items-center bg-black/50'
		>
			<div className='relative w-full max-w-md max-h-full'>
				<div className='relative  rounded-lg shadow bg-gray-700'>
					<button
						type='button'
						className='absolute top-3 right-2.5 text-gray-400 bg-transparent rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center hover:bg-gray-600 hover:text-white'
						data-modal-hide='authentication-modal'
						onClick={() => setIsOpen(false)}
					>
						<svg
							className='w-3 h-3'
							aria-hidden='true'
							xmlns='http://www.w3.org/2000/svg'
							fill='none'
							viewBox='0 0 14 14'
						>
							<path
								stroke='currentColor'
								strokeLinecap='round'
								strokeLinejoin='round'
								strokeWidth='2'
								d='m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6'
							/>
						</svg>
						<span className='sr-only'>Close modal</span>
					</button>
					<div className='px-6 py-6 lg:px-8'>
						<h2 className='text-2xl mb-4 border-b border-gray-200'>Pictionary Rules</h2>
						<p>
							In Pictionary, players split into two teams, with each team taking turns guessing the secret word given by the word generator based on the drawing of one of the players.
							The word generator on the app randomly generates a word or phrase, which the drawing player will need to illustrate to their team without revealing the word. The drawing
							player then has a limited time, typically one minute, to draw a picture on that represents the word or phrase generated by the app. Team members must guess the word or
							phrase based on the drawing within the time limit. If they guess correctly, their team earns points; if not, play passes to the other team. The team that accumulates the
							most points by successfully guessing words or phrases through drawings wins the game. Pictionary with a digital word generator adds a modern twist to the classic game while
							maintaining its creative and competitive spirit.
						</p>
					</div>
				</div>
			</div>
		</div>
	);
};
